apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-deployment
  template:
    metadata:
      labels:
        app: echo-deployment
    spec:
      containers:
      - name: echo-deployment
        image: inanimate/echo-server
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
  