version: '3.8'

services:
  mongo-node-1:
    image: mongo
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo-node-1:/data/db
    networks:
      - mongo-network
    ports:
      - "27017:27017"

  mongo-node-2:
    image: mongo
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo-node-2:/data/db
    networks:
      - mongo-network
    ports:
      - "27018:27017"

  mongo-node-3:
    image: mongo
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo-node-3:/data/db
    networks:
      - mongo-network
    ports:
      - "27019:27017"

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-node-1:
  mongo-node-2:
  mongo-node-3: